### ISSUE TITLE
What's the difference between rainy_vid and rainy_vid_blur?

### ISSUE THREAD

**Issue by Ssakura-go** [csqiangwen/Video_Waterdrop_Removal_in_Driving_Scenes#1]
Dear author,
I'd like to try your proposed model on my own dataset. But I don't know the difference between dataset rainy_vid and rainy_vid_blur and have no idea how to get the blur images. Could you please give me some advice?
Hope for your quick reply!
Best wishes to you!

**Comment by csqiangwen** [comment]
The only difference between the "rainy_vid_blur" and "rainy_vid" is that : To generate "rainy_vid_blur", we add "Gaussian Blur" before we add synthetic waterdrops on the clean vid.
The main reason: we realize that in real-world cases, the rain in the air makes the background information blurry which motivates us to enhance the "clean background" by a deblurring process.

**Comment by Ssakura-go** [comment]
> The only difference between the "rainy_vid_blur" and "rainy_vid" is that : To generate "rainy_vid_blur", we add "Gaussian Blur" before we add synthetic waterdrops on the clean vid. The main reason: we realize that in real-world cases, the rain in the air makes the background information blurry which motivates us to enhance the "clean background" by a deblurring process.

Roger that! Thanks for your quick reply!
