### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './dataset/train/train_img/train/data

### ISSUE THREAD

**Issue by Oldknife365** [csqiangwen/Video_Waterdrop_Removal_in_Driving_Scenes#3]
Dear author,
I just wanted to say thanks for creating and sharing your project on GitHub. It's been really helpful to me.
I did have a question about your project, though. When I downloaded the dataset you provided and tried to train the model. An error occured "FileNotFoundError: [Errno 2] No such file or directory: './dataset/train/train_img/train/data'", it seems like you maybe forget to upload the data in above directory but only the "./dataet/train/train_vid".
If you have a few minutes to spare, I would really appreciate any guidance or direction you could provide on this issue. Thanks again for your awesome work and for taking the time to read this message.
Best wishes.

**Comment by csqiangwen** [comment]
Sorry for the late reply. For the 'train_img/train/data', you can download it [here](https://github.com/rui1996/DeRaindrop).

**Comment by fanwu66** [comment]
> Sorry for the late reply. For the 'train_img/train/data', you can download it [here](https://github.com/rui1996/DeRaindrop).

Dear author,
I follow you and download it.but i meet new error:
Traceback (most recent call last):
  File "./train.py", line 21, in <module>
    vid_train_loader, img_train_loader = CreateDataLoader(opt)
  File "/home/wufan/Video_Waterdrop_Removal_in_Driving_Scenes/data/custom_dataset_data_loader.py", line 10, in CreateDataLoader
    img_train_dataset = Img_Train_RainDropDataset(opt)
  File "/home/wufan/Video_Waterdrop_Removal_in_Driving_Scenes/data/img_train_dataset.py", line 23, in __init__
    self.mask_names = natsorted(os.listdir(self.mask_path))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/train/train_img/train/mask'

Could you please provide make for me.
best wishes.
