### ISSUE TITLE
请问论文中提到的真实世界的图像数据集是什么数据集？

### ISSUE THREAD

**Issue by RussLoveHitIron** [csqiangwen/Video_Waterdrop_Removal_in_Driving_Scenes#4]
我看到Github上发布的数据集只有train_vid视频训练集，但是代码和论文中都有一个联合训练的图像数据集，但是我并未发现提供的数据集中有train_img这一选项。

**Comment by csqiangwen** [comment]
你好，“train_img”数据集来自于[这项工作](https://github.com/rui1996/DeRaindrop)，其中image的mask的生成也同样参照了该工作中的描述。

**Comment by RussLoveHitIron** [comment]
非常感谢！
