### ISSUE TITLE
只使用train_vid训练集进行训练时，在真实场景下的测试效果很差

### ISSUE THREAD

**Issue by RussLoveHitIron** [csqiangwen/Video_Waterdrop_Removal_in_Driving_Scenes#5]
作者您好，您在论文中提到模型是用一个train_img和一个train_vid进行联合训练得到，但是我发现在train_img这个训练集上（您之前在issues里给出的下载地址）是没有mask这一项的，但是代码的dataloader是有读取mask这一操作的。不知您能否提供包含mask的train_img训练集？
此外，我注释掉了代码中关于train_img训练集的一些相关代码，即只使用train_vid进行训练。在进行了与论文中同样的迭代次数后，我对test/syn和test/real分别进行了测试，其中对于test/syn的结果是符合论文结果的，但是对于test/real即真实场景的图片下的测试效果很不理想，几乎无法正常消除雨滴。
请问这是因为没有与自然图片train_img联合训练造成的影响吗？又或者是我忽略了哪些细节呢？恳请作者解惑！

**Comment by csqiangwen** [comment]
1. 由于train_vid（合成数据集）只能模拟椭圆形的小水滴，因此只使用train_vid（合成数据集）训练出来的模型无法处理好现实中更复杂的情况。但该模型依旧能够处理现实情况下出现的椭圆形小水滴。如果需要处理更复杂的现实场景，建议在训练时引入train_img（真实数据集）;
2. 目前train_img（真实数据集）已经上传，放在和train_vid（合成数据集）同一路径下。
